first commit the component select
frontendcafe/air-flashcards pull request #115
Opened 2022-09-01 11:45 UTC by gustavoisaacc

## Feature name
[Description]

### Issue number
- #ISSUE_NUMBER

### Screenshots
[Upload an image/video about the functionallity that you're adding]

### Notes / Known issues
[Extra comments]

### Tasks
- [ ] Assing this PR to you
- [ ] Add label for corresponding module
- [ ] Link the issue in Development section
- [ ] Send this pr to your teammates

2022-09-03 20:46 UTC, AnibalDBXD requested changes
Veo bien el componente, te deje unos cambios para que pueda ser utilizado

2022-09-03 20:46 UTC, AnibalDBXD commented on modules/shared/components/Select.tsx
> +      <Select placeholder="Select option">
Y utilizar esas props, para que podamos tambien pasarle las props de `value`, `onChange` etc..

```suggestion
const ComponentSelect = ({ label, option, ...props }: Props) => {
  return (
    <>
      <label htmlFor={label}>{label}</label>
      <Select {...props} placeholder="Select option">
```

2022-09-03 20:46 UTC, AnibalDBXD commented on modules/shared/components/Select.tsx
> +interface Category {
Podrias cambiarlo el nombre a `Props` o `SelectProps`

E importar los props del select de chakra para poder utilizarlos tambien en el componente

```suggestion
import { Select, SelectProps } from "@chakra-ui/react";

interface Props extends SelectProps {
```

2022-09-04 00:16 UTC, AnibalDBXD approved these changes

2022-09-05 14:08 UTC, 9gustin approved these changes

2022-09-05 21:59 UTC, merged