Main feature/95 mis colecciones
frontendcafe/air-flashcards pull request #118
Opened 2022-09-02 21:14 UTC by nicodeheza

## Feature name
 Pagina de colecciones del usuario

### Issue number
- #95

### Screenshots
![Captura de pantalla 2022-09-02 174428](https://user-images.githubusercontent.com/66743724/188235602-06effb71-7ee8-47d3-a655-3192d8f57ace.png)
![Captura de pantalla 2022-09-02 174529](https://user-images.githubusercontent.com/66743724/188235606-3fcdf864-7468-4911-8b4e-4e3fe72d75e7.png)
![Captura de pantalla 2022-09-02 180919](https://user-images.githubusercontent.com/66743724/188235607-f1b47af3-af68-42f2-828d-c54295a486e9.png)

### Notes / Known issues
En el diseño las colecciones tienen tags, yo hardcordie un texto. Pero habria que agregar al esquema de la colecciones dichos tags. 

### Tasks
- [x] Assing this PR to you
- [x] Add label for corresponding module
- [x] Link the issue in Development section
- [x] Send this pr to your teammates

2022-09-02 21:29 UTC, 9gustin approved these changes
Nice! ✅

2022-09-02 21:29 UTC, 9gustin commented on pages/api/collections/user/[id].tsx
> +  const collections = await getCollectionsByUserId(request.query.id as string);
la vulnerabilidad que tiene esto es que cualquier usuario podria obtener colecciones de otros usuarios, pero por tiempos diria que ya fue, asumamoslo

2022-09-02 21:29 UTC, 9gustin commented on modules/Collections/getCollectionStudySessions.ts
> +  //   console.log(studySessions);
```suggestion
```

2022-09-02 22:04 UTC, kevin-dev71 approved these changes

2022-09-02 23:09 UTC, nicodeheza commented on pages/api/collections/user/[id].tsx
> +  const collections = await getCollectionsByUserId(request.query.id as string);
Yo por mí lo cambio. Pero hay algún modo de opener el Id del usuario en el backend ? Por hasta donde vi no tenemos secciones en el back ni encontré ninguna cookie en el request

2022-09-02 23:42 UTC, 9gustin commented on pages/api/collections/user/[id].tsx
> +  const collections = await getCollectionsByUserId(request.query.id as string);
Claro, no se bien como esta implementado, asi que tranki, no hay drama

2022-09-05 21:56 UTC, iarabaya requested changes

2022-09-05 21:56 UTC, iarabaya commented on modules/Collections/MyCollectionsPage/colletionList/CollectionItem.tsx
> +            {collection.name}
Aca deberia ser el collection.title? Por el model de Collections

2022-09-05 22:20 UTC, 9gustin reviewed
Otro comment, estuve revisando la rama y todo nice, cambiaria la ruta de la pagina, movamosla reemplazando al home 😄

2022-09-05 22:22 UTC, nicodeheza commented on modules/Collections/MyCollectionsPage/colletionList/CollectionItem.tsx
> +            {collection.name}
uh... jejeje ahí lo cambio

2022-09-05 22:25 UTC, nicodeheza commented on modules/Collections/MyCollectionsPage/colletionList/CollectionItem.tsx
> +            {collection.name}
Claro yo en local lo tenia como name. Ahi actualizo mi repo y lo cambio

2022-09-05 22:47 UTC, nicodeheza commented on modules/Collections/MyCollectionsPage/colletionList/CollectionItem.tsx
> +            {collection.name}
Listo. 
![Captura de pantalla 2022-09-05 194055](https://user-images.githubusercontent.com/66743724/188518316-756907bf-7730-45e9-ac31-f1b24955f66c.png)

2022-09-05 23:57 UTC, 9gustin approved these changes

2022-09-06 00:06 UTC, iarabaya commented on modules/Collections/MyCollectionsPage/NoCollections.tsx
> +        Aun no tienes coleccionse
colecciones, es un detallito nomas jaja

2022-09-06 00:08 UTC, iarabaya approved these changes
genial!

2022-09-06 00:17 UTC, 9gustin commented on modules/Collections/MyCollectionsPage/NoCollections.tsx
> +        Aun no tienes coleccionse
atajo para modificarlo

```suggestion
        Aun no tienes colecciones
```

2022-09-06 22:40 UTC, merged