issue 19 - AuthGuard Component, requiresAuthentication and redirectIf…
frontendcafe/air-flashcards pull request #50
Opened 2022-08-13 19:50 UTC by AnaliaAlvarez

- Creo el componente `AuthGuard` para redirigir al usuario si esta autenticado con FireBase usando la propiedad `redirectIfAuthenticated`. Tambien redirige al usuario no autenticado usando la propiedad `requiresAuthentication`.
- `requiresAuthentication` y `redirectIfAuthenticated` se asignan en los componentes de las pages de nextjs. Ej:

```typescript
LoginPage.redirectIfAuthenticated = true

export default LoginPage;
```

### Issue number
  [- #19 ](https://github.com/frontendcafe/air-flashcards/issues/19)

2022-08-13 20:11 UTC, kevin-dev71 approved these changes
lso `redirectUrl` y `authenticationType`  vamos a tener q manejarlo con enums o en un archivo de constantes para evitar futuros problemas de typos y que sea mas mantenible, pero de resto lo veo bien. Dejo aprobado mientras

2022-08-13 20:46 UTC, AnibalDBXD requested changes
Buen trabajo! deje varias sugerencias sobre como podrias tipar algunos componentes 👍 

Lo unico que te pediria que cambiases es el lugar del componente `AuthGuard`

2022-08-13 20:46 UTC, AnibalDBXD commented on components/AuthGuard.tsx
> +}
Buen Trabajo! Aunque este componente deberia ir en `modules/shared/AuthGuard.tsx` (Las convenciones de como manejamos la estrucutra de archivos esta en el readme

https://github.com/frontendcafe/air-flashcards#estructura-de-carpetas

2022-08-13 20:46 UTC, AnibalDBXD commented on components/AuthGuard.tsx
> +export const AuthGuard = ({ children, redirectUrl, authenticationType }: any) => {
Una sugerencia de como podias typar esto seria:

```ts
interface AuthGuardProps {
   children: ReactNode;
   redirectUrl: string;
   authenticationType: string; // en vez de un string podriamos cambiarlo a un enum pero un string servira por ahroa
}

export const AuthGuard: React.FC<AuthGuardProps > = ({ children, redirectUrl, authenticationType }) => ...
```

2022-08-13 20:46 UTC, AnibalDBXD commented on pages/_app.tsx
> +const MyApp = ({ Component, pageProps }: AppProps | any) => {
Podrias copiar los tipos que dejo kevin en unos de los comentarios que hizo en la issue para tipar esta parte 👀

2022-08-14 16:18 UTC, AnaliaAlvarez commented on components/AuthGuard.tsx
> +}
Ok! Listo!

2022-08-14 16:19 UTC, AnaliaAlvarez commented on components/AuthGuard.tsx
> +export const AuthGuard = ({ children, redirectUrl, authenticationType }: any) => {
En lugar de ReactNode usé JSX.Element porque sino no compilaba

2022-08-14 16:20 UTC, AnaliaAlvarez commented on pages/_app.tsx
> +const MyApp = ({ Component, pageProps }: AppProps | any) => {
Perfecto! Listo!

2022-08-14 16:57 UTC, AnibalDBXD approved these changes
Buen trabajo!

2022-08-14 18:56 UTC, kevin-dev71 approved these changes

2022-08-14 23:35 UTC, merged